# Generated by Django 3.0.6 on 2020-06-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200628_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppername', models.CharField(max_length=100)),
                ('topperclass', models.IntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('toppermarks', models.FloatField()),
                ('topperadvise', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
