# Generated by Django 3.0.6 on 2020-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_topper'),
    ]

    operations = [
        migrations.AddField(
            model_name='topper',
            name='topperimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
