# Generated by Django 3.0.6 on 2020-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_topper_topperimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='topper',
            name='topperyear',
            field=models.IntegerField(null=True),
        ),
    ]
