# Generated by Django 3.0.6 on 2020-06-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20200629_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-published']},
        ),
    ]
