# Generated by Django 3.0.6 on 2020-06-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20200629_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topper',
            name='topperimg',
        ),
        migrations.AddField(
            model_name='topper',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
