# Generated by Django 3.0.6 on 2020-06-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20200629_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topper',
        ),
    ]
